[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "aave-v3-core/=lib/aave-v3-core/",
    "aave-v3-periphery/=lib/aave-v3-periphery/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/"    
]

[rpc_endpoints]
# main networks
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
# test networks
goerli = "${RPC_GOERLI}"
mumbai = "${RPC_MUMBAI}"


[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chainId = 1 }
goerli = { key = "${ETHERSCAN_API_KEY}", chainId = 5 }
polygon = { key = "${POLYGONSCAN_API_KEY}", chainId = 137 }
mumbai = { key = "${POLYGONSCAN_API_KEY}", chainId = 80001 }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config